data_path: data/banknote.csv

split:
  test_size: 0.2
  random_state: 42

model:
  type: xgboost
  params:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3

mlflow:
  tracking_uri: file://mlruns
  experiment_name: banknote_classification