name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: make test

      # Crear el directorio 'mlruns' antes de entrenar el modelo
      - name: Create MLflow directory
        run: |
          mkdir -p mlruns

      - name: Train model
        run: make train

      - name: Upload model to MLflow
        run: |
          mlflow ui --host 0.0.0.0 --port 5000