name: ML Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de que todas las dependencias estén en requirements.txt

      - name: Run tests
        run: make test  

      - name: Create MLflow directory
        run: |
          mkdir -p mlruns  # Crear el directorio mlruns, que se usará para guardar el modelo entrenado

      - name: Train and log model with MLflow
        run: |
          python src/train.py  # Ejecutamos tu script para entrenar el modelo y registrarlo en MLflow

      - name: Upload MLflow model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model  # Nombre del artefacto
          path: mlruns/  # Directorio donde MLflow guarda el modelo
